# Generated by Django 5.2.7 on 2025-10-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='styles',
            field=models.FileField(blank=True, upload_to='styles/%Y/%m/%d/', verbose_name='CSS styles'),
        ),
    ]
