# Generated by Django 5.2.7 on 2025-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_profile_styles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="styles",
            field=models.FileField(
                blank=True,
                upload_to="styles/%Y/%m/%d/",
                verbose_name="CSS стили",
            ),
        ),
    ]
