# Generated by Django 5.2.7 on 2025-11-06 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(verbose_name="Действителен с"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(verbose_name="Действителен до"),
                ),
                (
                    "discount",
                    models.IntegerField(
                        help_text="Значение в % (от 0 до 100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Скидка",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="Действие")),
            ],
            options={
                "verbose_name": "Купон",
                "verbose_name_plural": "Купоны",
            },
        ),
    ]
