# Generated by Django 5.2.7 on 2025-10-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="verb",
            field=models.CharField(max_length=255, verbose_name="Действие"),
        ),
    ]
