# Generated by Django 5.2.7 on 2025-10-19 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('title', models.CharField(
                    max_length=250,
                    verbose_name='Название',
                )),
                ('slug', models.SlugField(
                    max_length=250,
                    verbose_name='Слаг',
                )),
                ('body', models.TextField(verbose_name='Тело')),
                ('publish', models.DateTimeField(
                    default=django.utils.timezone.now,
                    verbose_name='Дата публикации',
                )),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(
                    choices=[('DF', 'Черновик'), ('PB', 'Опубликовать')],
                    default='DF',
                    max_length=2,
                    verbose_name='Статус',
                )),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='blog_posts',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Автор',
                )),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('-publish',),
                'indexes': [models.Index(
                    fields=['-publish'],
                    name='blog_post_publish_bb7600_idx',
                )],
            },
        ),
    ]
