# Generated by Django 5.2.7 on 2025-10-20 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name='Created date',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='Published date',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(
                choices=[('DF', 'Черновик'), ('PB', 'Published')],
                default='DF',
                max_length=2,
                verbose_name='Статус',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name='Updated date'
            ),
        ),
    ]
