# Generated by Django 5.2.7 on 2025-10-20 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_alter_post_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name='Дата создания',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='Дата публикации',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(
                max_length=250,
                unique_for_date='publish',
                verbose_name='Слаг',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(
                choices=[('DF', 'Черновик'), ('PB', 'Опубликован')],
                default='DF', 
                max_length=2,
                verbose_name='Статус',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name='Дата обновления',
            ),
        ),
    ]
