# Generated by Django 5.2.7 on 2025-10-21 11:43

import taggit.managers  # type: ignore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment"),
        (
            "taggit",
            (
                "0006_rename_taggeditem_content_type_o"
                "bject_id_taggit_tagg_content_8fc721_idx"
            ),
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created"],
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=80, verbose_name="Имя"),
        ),
    ]
