# Generated by Django 5.2.7 on 2025-10-22 12:57

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_comment_options_post_tags_alter_comment_name"),
    ]

    operations = [TrigramExtension()]
