# Generated by Django 5.2.7 on 2025-10-28 10:17

from django.conf import settings
from django.db import migrations, models


def add_total_likes(apps, schema_editor):
    Image = apps.get_model("images", "Image")
    # Здесь ваша логика, например, перенос данных
    for instance in Image.objects.annotate(likes=models.Count("users_like")):
        instance.total_likes = instance.likes
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="total_likes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Общее количество лайков"
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["-total_likes"], name="images_imag_total_l_0bcd7e_idx"
            ),
        ),
        migrations.RunPython(add_total_likes, migrations.RunPython.noop),
    ]
